package com.example.spring_12_15.Model;

import java.math.BigDecimal;

/**
 * ❶ Domain model representing a row in the "purchase" table.
 *    Each instance of this class corresponds to one record.
 */
public class Purchase {

    // ❷ ID is generated by the database (AUTO_INCREMENT)
    private int id;

    // ❸ Name of the purchased product
    private String product;

    // ❹ Using BigDecimal for money to avoid precision issues
    private BigDecimal price;

    // ❺ Default constructor (required by some frameworks and for deserialization)
    public Purchase() {
    }

    // ❻ Convenience constructor (not mandatory, but often useful)
    public Purchase(int id, String product, BigDecimal price) {
        this.id = id;
        this.product = product;
        this.price = price;
    }

    // ❼ Getters and setters

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }


    public String getProduct() {
        return product;
    }

    public void setProduct(String product) {
        this.product = product;
    }


    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    // ❽ toString for easier logging / debugging
    @Override
    public String toString() {
        return "Purchase{" +
                "id=" + id +
                ", product='" + product + '\'' +
                ", price=" + price +
                '}';
    }
}
